apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-functions-auth
  description: TypeScript package for adding OAuth2 to Azure Functions
  annotations:
    github.com/project-slug: rvohealth/azure-functions-auth
spec:
  type: service # can be one of: service, library, website, event-driven-service, terraform-module, terraform-repo
  lifecycle: production # can be one of: experimental, production, deprecated
  owner: team-aaavang # your existing tech team, i.e. team-developer-platforms
